import type { User, Subject, Question, Exam, ExamField } from "./types"

export const mockUser: User = {
  id: "1",
  email: "student@example.com",
  full_name: "Abebe Kebede",
  role: "student",
  field: "natural",
  batch: "2024-A",
  created_at: new Date().toISOString(),
}

export const mockSubjects: Subject[] = [
  { id: "math", name: "Mathematics", field: "natural", description: "Advanced mathematics for natural sciences" },
  { id: "physics", name: "Physics", field: "natural", description: "Fundamental physics concepts" },
  { id: "chemistry", name: "Chemistry", field: "natural", description: "General and organic chemistry" },
  { id: "biology", name: "Biology", field: "natural", description: "Life sciences and biology" },
  { id: "history", name: "History", field: "social", description: "Ethiopian and world history" },
  { id: "geography", name: "Geography", field: "social", description: "Physical and human geography" },
  { id: "economics", name: "Economics", field: "social", description: "Basic economic principles" },
  { id: "civics", name: "Civics", field: "social", description: "Civics and ethical education" },
]

export const mockQuestions: Question[] = [
  {
    id: "1",
    subject_id: "math",
    question_text: "What is the derivative of x² + 3x + 2?",
    question_type: "multiple_choice",
    difficulty_level: 2,
    explanation: "Using the power rule: d/dx(x²) = 2x, d/dx(3x) = 3, d/dx(2) = 0. Therefore, the derivative is 2x + 3.",
    created_at: new Date().toISOString(),
    options: [
      { id: "1a", question_id: "1", option_text: "2x + 3", is_correct: true, option_order: 1 },
      { id: "1b", question_id: "1", option_text: "x² + 3", is_correct: false, option_order: 2 },
      { id: "1c", question_id: "1", option_text: "2x + 2", is_correct: false, option_order: 3 },
      { id: "1d", question_id: "1", option_text: "x + 3", is_correct: false, option_order: 4 },
    ],
  },
  {
    id: "2",
    subject_id: "math",
    question_text: "Solve for x: 2x + 5 = 13",
    question_type: "multiple_choice",
    difficulty_level: 1,
    explanation: "Subtract 5 from both sides: 2x = 8. Then divide both sides by 2: x = 4.",
    created_at: new Date().toISOString(),
    options: [
      { id: "2a", question_id: "2", option_text: "4", is_correct: true, option_order: 1 },
      { id: "2b", question_id: "2", option_text: "8", is_correct: false, option_order: 2 },
      { id: "2c", question_id: "2", option_text: "3", is_correct: false, option_order: 3 },
      { id: "2d", question_id: "2", option_text: "9", is_correct: false, option_order: 4 },
    ],
  },
  {
    id: "3",
    subject_id: "physics",
    question_text: "What is Newton's Second Law of Motion?",
    question_type: "multiple_choice",
    difficulty_level: 2,
    explanation:
      "Newton's Second Law states that Force equals mass times acceleration (F = ma). This fundamental law describes how the motion of an object changes when forces are applied.",
    created_at: new Date().toISOString(),
    options: [
      { id: "3a", question_id: "3", option_text: "F = ma", is_correct: true, option_order: 1 },
      { id: "3b", question_id: "3", option_text: "E = mc²", is_correct: false, option_order: 2 },
      { id: "3c", question_id: "3", option_text: "F = G(m₁m₂)/r²", is_correct: false, option_order: 3 },
      { id: "3d", question_id: "3", option_text: "v = u + at", is_correct: false, option_order: 4 },
    ],
  },
  {
    id: "4",
    subject_id: "chemistry",
    question_text: "What is the chemical formula for water?",
    question_type: "multiple_choice",
    difficulty_level: 1,
    explanation: "Water consists of two hydrogen atoms bonded to one oxygen atom, giving it the chemical formula H₂O.",
    created_at: new Date().toISOString(),
    options: [
      { id: "4a", question_id: "4", option_text: "H₂O", is_correct: true, option_order: 1 },
      { id: "4b", question_id: "4", option_text: "CO₂", is_correct: false, option_order: 2 },
      { id: "4c", question_id: "4", option_text: "O₂", is_correct: false, option_order: 3 },
      { id: "4d", question_id: "4", option_text: "H₂O₂", is_correct: false, option_order: 4 },
    ],
  },
  {
    id: "5",
    subject_id: "biology",
    question_text: "What is the powerhouse of the cell?",
    question_type: "multiple_choice",
    difficulty_level: 1,
    explanation:
      "Mitochondria are known as the powerhouse of the cell because they generate most of the cell's supply of ATP (adenosine triphosphate), which is used as a source of chemical energy.",
    created_at: new Date().toISOString(),
    options: [
      { id: "5a", question_id: "5", option_text: "Mitochondria", is_correct: true, option_order: 1 },
      { id: "5b", question_id: "5", option_text: "Nucleus", is_correct: false, option_order: 2 },
      { id: "5c", question_id: "5", option_text: "Ribosome", is_correct: false, option_order: 3 },
      { id: "5d", question_id: "5", option_text: "Chloroplast", is_correct: false, option_order: 4 },
    ],
  },
  {
    id: "6",
    subject_id: "history",
    question_text: "In which year did Ethiopia defeat Italy at the Battle of Adwa?",
    question_type: "multiple_choice",
    difficulty_level: 2,
    explanation:
      "The Battle of Adwa took place on March 1, 1896, where Ethiopian forces decisively defeated the Italian army, securing Ethiopia's sovereignty.",
    created_at: new Date().toISOString(),
    options: [
      { id: "6a", question_id: "6", option_text: "1896", is_correct: true, option_order: 1 },
      { id: "6b", question_id: "6", option_text: "1889", is_correct: false, option_order: 2 },
      { id: "6c", question_id: "6", option_text: "1906", is_correct: false, option_order: 3 },
      { id: "6d", question_id: "6", option_text: "1882", is_correct: false, option_order: 4 },
    ],
  },
  // Additional Mathematics Questions for 2024 Exam
  // Derivation Questions
  {
    id: "7",
    subject_id: "math",
    question_text: "Find the derivative of f(x) = (x³ + 2x² - 5x + 1) using the power rule.",
    question_type: "multiple_choice",
    difficulty_level: 2,
    explanation: "Using the power rule: d/dx(x³) = 3x², d/dx(2x²) = 4x, d/dx(-5x) = -5, d/dx(1) = 0. Therefore, f'(x) = 3x² + 4x - 5.",
    created_at: new Date().toISOString(),
    options: [
      { id: "7a", question_id: "7", option_text: "3x² + 4x - 5", is_correct: true, option_order: 1 },
      { id: "7b", question_id: "7", option_text: "3x² + 2x - 5", is_correct: false, option_order: 2 },
      { id: "7c", question_id: "7", option_text: "x² + 4x - 5", is_correct: false, option_order: 3 },
      { id: "7d", question_id: "7", option_text: "3x² + 4x + 1", is_correct: false, option_order: 4 },
    ],
  },
  {
    id: "8",
    subject_id: "math",
    question_text: "What is the derivative of f(x) = (2x + 3)⁴ using the chain rule?",
    question_type: "multiple_choice",
    difficulty_level: 3,
    explanation: "Using the chain rule: f'(x) = 4(2x + 3)³ × d/dx(2x + 3) = 4(2x + 3)³ × 2 = 8(2x + 3)³.",
    created_at: new Date().toISOString(),
    options: [
      { id: "8a", question_id: "8", option_text: "8(2x + 3)³", is_correct: true, option_order: 1 },
      { id: "8b", question_id: "8", option_text: "4(2x + 3)³", is_correct: false, option_order: 2 },
      { id: "8c", question_id: "8", option_text: "2(2x + 3)³", is_correct: false, option_order: 3 },
      { id: "8d", question_id: "8", option_text: "16(2x + 3)³", is_correct: false, option_order: 4 },
    ],
  },
  {
    id: "9",
    subject_id: "math",
    question_text: "Find the derivative of f(x) = x²sin(x) using the product rule.",
    question_type: "multiple_choice",
    difficulty_level: 3,
    explanation: "Using the product rule: f'(x) = d/dx(x²) × sin(x) + x² × d/dx(sin(x)) = 2x × sin(x) + x² × cos(x) = 2x sin(x) + x² cos(x).",
    created_at: new Date().toISOString(),
    options: [
      { id: "9a", question_id: "9", option_text: "2x sin(x) + x² cos(x)", is_correct: true, option_order: 1 },
      { id: "9b", question_id: "9", option_text: "2x cos(x) + x² sin(x)", is_correct: false, option_order: 2 },
      { id: "9c", question_id: "9", option_text: "x² sin(x) + 2x cos(x)", is_correct: false, option_order: 3 },
      { id: "9d", question_id: "9", option_text: "2x sin(x) - x² cos(x)", is_correct: false, option_order: 4 },
    ],
  },
  {
    id: "10",
    subject_id: "math",
    question_text: "What is the derivative of f(x) = (x² + 1)/(x - 2) using the quotient rule?",
    question_type: "multiple_choice",
    difficulty_level: 3,
    explanation: "Using the quotient rule: f'(x) = [(2x)(x-2) - (x²+1)(1)]/(x-2)² = [2x²-4x-x²-1]/(x-2)² = (x²-4x-1)/(x-2)².",
    created_at: new Date().toISOString(),
    options: [
      { id: "10a", question_id: "10", option_text: "(x² - 4x - 1)/(x - 2)²", is_correct: true, option_order: 1 },
      { id: "10b", question_id: "10", option_text: "(2x - 1)/(x - 2)²", is_correct: false, option_order: 2 },
      { id: "10c", question_id: "10", option_text: "(x² + 4x + 1)/(x - 2)²", is_correct: false, option_order: 3 },
      { id: "10d", question_id: "10", option_text: "(2x + 1)/(x - 2)²", is_correct: false, option_order: 4 },
    ],
  },
  // Integration Questions
  {
    id: "11",
    subject_id: "math",
    question_text: "Evaluate ∫(3x² + 2x - 1)dx",
    question_type: "multiple_choice",
    difficulty_level: 2,
    explanation: "Using the power rule for integration: ∫(3x² + 2x - 1)dx = 3(x³/3) + 2(x²/2) - x + C = x³ + x² - x + C.",
    created_at: new Date().toISOString(),
    options: [
      { id: "11a", question_id: "11", option_text: "x³ + x² - x + C", is_correct: true, option_order: 1 },
      { id: "11b", question_id: "11", option_text: "3x³ + 2x² - x + C", is_correct: false, option_order: 2 },
      { id: "11c", question_id: "11", option_text: "x³ + x² + x + C", is_correct: false, option_order: 3 },
      { id: "11d", question_id: "11", option_text: "6x + 2 + C", is_correct: false, option_order: 4 },
    ],
  },
  {
    id: "12",
    subject_id: "math",
    question_text: "Evaluate ∫₀² (2x + 3)dx",
    question_type: "multiple_choice",
    difficulty_level: 2,
    explanation: "First find the antiderivative: ∫(2x + 3)dx = x² + 3x + C. Then evaluate from 0 to 2: [2² + 3(2)] - [0² + 3(0)] = [4 + 6] - [0] = 10.",
    created_at: new Date().toISOString(),
    options: [
      { id: "12a", question_id: "12", option_text: "10", is_correct: true, option_order: 1 },
      { id: "12b", question_id: "12", option_text: "8", is_correct: false, option_order: 2 },
      { id: "12c", question_id: "12", option_text: "12", is_correct: false, option_order: 3 },
      { id: "12d", question_id: "12", option_text: "6", is_correct: false, option_order: 4 },
    ],
  },
  {
    id: "13",
    subject_id: "math",
    question_text: "Evaluate ∫(x² + 1)² dx using substitution.",
    question_type: "multiple_choice",
    difficulty_level: 3,
    explanation: "Let u = x² + 1, then du = 2x dx. The integral becomes ∫u²(du/2x) = (1/2)∫u² du = (1/2)(u³/3) + C = (1/6)(x² + 1)³ + C.",
    created_at: new Date().toISOString(),
    options: [
      { id: "13a", question_id: "13", option_text: "(1/6)(x² + 1)³ + C", is_correct: true, option_order: 1 },
      { id: "13b", question_id: "13", option_text: "(1/3)(x² + 1)³ + C", is_correct: false, option_order: 2 },
      { id: "13c", question_id: "13", option_text: "(x² + 1)³ + C", is_correct: false, option_order: 3 },
      { id: "13d", question_id: "13", option_text: "(1/2)(x² + 1)³ + C", is_correct: false, option_order: 4 },
    ],
  },
  // Algebra Questions
  {
    id: "14",
    subject_id: "math",
    question_text: "Solve the quadratic equation: x² - 5x + 6 = 0",
    question_type: "multiple_choice",
    difficulty_level: 2,
    explanation: "Factor the quadratic: (x - 2)(x - 3) = 0. Therefore, x = 2 or x = 3.",
    created_at: new Date().toISOString(),
    options: [
      { id: "14a", question_id: "14", option_text: "x = 2, x = 3", is_correct: true, option_order: 1 },
      { id: "14b", question_id: "14", option_text: "x = -2, x = -3", is_correct: false, option_order: 2 },
      { id: "14c", question_id: "14", option_text: "x = 1, x = 6", is_correct: false, option_order: 3 },
      { id: "14d", question_id: "14", option_text: "x = 0, x = 5", is_correct: false, option_order: 4 },
    ],
  },
  {
    id: "15",
    subject_id: "math",
    question_text: "Solve the system of equations: 2x + 3y = 7, x - y = 1",
    question_type: "multiple_choice",
    difficulty_level: 2,
    explanation: "From the second equation: x = y + 1. Substitute into the first: 2(y + 1) + 3y = 7, so 2y + 2 + 3y = 7, 5y = 5, y = 1. Then x = 1 + 1 = 2.",
    created_at: new Date().toISOString(),
    options: [
      { id: "15a", question_id: "15", option_text: "x = 2, y = 1", is_correct: true, option_order: 1 },
      { id: "15b", question_id: "15", option_text: "x = 1, y = 2", is_correct: false, option_order: 2 },
      { id: "15c", question_id: "15", option_text: "x = 3, y = 0", is_correct: false, option_order: 3 },
      { id: "15d", question_id: "15", option_text: "x = 0, y = 3", is_correct: false, option_order: 4 },
    ],
  },
  {
    id: "16",
    subject_id: "math",
    question_text: "Factor the polynomial: x³ - 8",
    question_type: "multiple_choice",
    difficulty_level: 3,
    explanation: "This is a difference of cubes: x³ - 8 = x³ - 2³ = (x - 2)(x² + 2x + 4).",
    created_at: new Date().toISOString(),
    options: [
      { id: "16a", question_id: "16", option_text: "(x - 2)(x² + 2x + 4)", is_correct: true, option_order: 1 },
      { id: "16b", question_id: "16", option_text: "(x + 2)(x² - 2x + 4)", is_correct: false, option_order: 2 },
      { id: "16c", question_id: "16", option_text: "(x - 2)(x² - 2x + 4)", is_correct: false, option_order: 3 },
      { id: "16d", question_id: "16", option_text: "(x + 2)(x² + 2x + 4)", is_correct: false, option_order: 4 },
    ],
  },
  // Geometry Questions
  {
    id: "17",
    subject_id: "math",
    question_text: "Find the area of a triangle with sides 3, 4, and 5 units.",
    question_type: "multiple_choice",
    difficulty_level: 2,
    explanation: "This is a right triangle (3² + 4² = 5²). Area = (1/2) × base × height = (1/2) × 3 × 4 = 6 square units.",
    created_at: new Date().toISOString(),
    options: [
      { id: "17a", question_id: "17", option_text: "6 square units", is_correct: true, option_order: 1 },
      { id: "17b", question_id: "17", option_text: "12 square units", is_correct: false, option_order: 2 },
      { id: "17c", question_id: "17", option_text: "15 square units", is_correct: false, option_order: 3 },
      { id: "17d", question_id: "17", option_text: "20 square units", is_correct: false, option_order: 4 },
    ],
  },
  {
    id: "18",
    subject_id: "math",
    question_text: "Find the circumference of a circle with radius 7 cm.",
    question_type: "multiple_choice",
    difficulty_level: 1,
    explanation: "Circumference = 2πr = 2π(7) = 14π cm.",
    created_at: new Date().toISOString(),
    options: [
      { id: "18a", question_id: "18", option_text: "14π cm", is_correct: true, option_order: 1 },
      { id: "18b", question_id: "18", option_text: "7π cm", is_correct: false, option_order: 2 },
      { id: "18c", question_id: "18", option_text: "49π cm", is_correct: false, option_order: 3 },
      { id: "18d", question_id: "18", option_text: "28π cm", is_correct: false, option_order: 4 },
    ],
  },
  {
    id: "19",
    subject_id: "math",
    question_text: "Find the distance between points A(1, 2) and B(4, 6) using the distance formula.",
    question_type: "multiple_choice",
    difficulty_level: 2,
    explanation: "Distance = √[(4-1)² + (6-2)²] = √[3² + 4²] = √[9 + 16] = √25 = 5 units.",
    created_at: new Date().toISOString(),
    options: [
      { id: "19a", question_id: "19", option_text: "5 units", is_correct: true, option_order: 1 },
      { id: "19b", question_id: "19", option_text: "7 units", is_correct: false, option_order: 2 },
      { id: "19c", question_id: "19", option_text: "3 units", is_correct: false, option_order: 3 },
      { id: "19d", question_id: "19", option_text: "4 units", is_correct: false, option_order: 4 },
    ],
  },
  {
    id: "20",
    subject_id: "math",
    question_text: "Find the volume of a cylinder with radius 3 cm and height 8 cm.",
    question_type: "multiple_choice",
    difficulty_level: 2,
    explanation: "Volume of cylinder = πr²h = π(3)²(8) = π(9)(8) = 72π cm³.",
    created_at: new Date().toISOString(),
    options: [
      { id: "20a", question_id: "20", option_text: "72π cm³", is_correct: true, option_order: 1 },
      { id: "20b", question_id: "20", option_text: "24π cm³", is_correct: false, option_order: 2 },
      { id: "20c", question_id: "20", option_text: "96π cm³", is_correct: false, option_order: 3 },
      { id: "20d", question_id: "20", option_text: "48π cm³", is_correct: false, option_order: 4 },
    ],
  },
  {
    id: "21",
    subject_id: "math",
    question_text: "What is the derivative of f(x) = e^(2x) using the chain rule?",
    question_type: "multiple_choice",
    difficulty_level: 3,
    explanation: "Using the chain rule: f'(x) = e^(2x) × d/dx(2x) = e^(2x) × 2 = 2e^(2x).",
    created_at: new Date().toISOString(),
    options: [
      { id: "21a", question_id: "21", option_text: "2e^(2x)", is_correct: true, option_order: 1 },
      { id: "21b", question_id: "21", option_text: "e^(2x)", is_correct: false, option_order: 2 },
      { id: "21c", question_id: "21", option_text: "e^(2x)/2", is_correct: false, option_order: 3 },
      { id: "21d", question_id: "21", option_text: "4e^(2x)", is_correct: false, option_order: 4 },
    ],
  },
  {
    id: "22",
    subject_id: "math",
    question_text: "Evaluate ∫₀¹ x² dx",
    question_type: "multiple_choice",
    difficulty_level: 2,
    explanation: "∫x² dx = x³/3 + C. Evaluating from 0 to 1: [1³/3] - [0³/3] = 1/3 - 0 = 1/3.",
    created_at: new Date().toISOString(),
    options: [
      { id: "22a", question_id: "22", option_text: "1/3", is_correct: true, option_order: 1 },
      { id: "22b", question_id: "22", option_text: "1/2", is_correct: false, option_order: 2 },
      { id: "22c", question_id: "22", option_text: "2/3", is_correct: false, option_order: 3 },
      { id: "22d", question_id: "22", option_text: "1", is_correct: false, option_order: 4 },
    ],
  },
  {
    id: "23",
    subject_id: "math",
    question_text: "Solve the equation: log₂(x + 3) = 4",
    question_type: "multiple_choice",
    difficulty_level: 3,
    explanation: "If log₂(x + 3) = 4, then x + 3 = 2⁴ = 16. Therefore, x = 16 - 3 = 13.",
    created_at: new Date().toISOString(),
    options: [
      { id: "23a", question_id: "23", option_text: "x = 13", is_correct: true, option_order: 1 },
      { id: "23b", question_id: "23", option_text: "x = 19", is_correct: false, option_order: 2 },
      { id: "23c", question_id: "23", option_text: "x = 7", is_correct: false, option_order: 3 },
      { id: "23d", question_id: "23", option_text: "x = 1", is_correct: false, option_order: 4 },
    ],
  },
  {
    id: "24",
    subject_id: "math",
    question_text: "Find the center and radius of the circle: x² + y² - 6x + 4y - 3 = 0",
    question_type: "multiple_choice",
    difficulty_level: 3,
    explanation: "Complete the square: (x² - 6x + 9) + (y² + 4y + 4) = 3 + 9 + 4 = 16. So (x-3)² + (y+2)² = 4². Center: (3, -2), Radius: 4.",
    created_at: new Date().toISOString(),
    options: [
      { id: "24a", question_id: "24", option_text: "Center: (3, -2), Radius: 4", is_correct: true, option_order: 1 },
      { id: "24b", question_id: "24", option_text: "Center: (-3, 2), Radius: 4", is_correct: false, option_order: 2 },
      { id: "24c", question_id: "24", option_text: "Center: (3, -2), Radius: 2", is_correct: false, option_order: 3 },
      { id: "24d", question_id: "24", option_text: "Center: (-3, 2), Radius: 2", is_correct: false, option_order: 4 },
    ],
  },
  // Graph Questions
  {
    id: "25",
    subject_id: "math",
    question_text: "What is the slope of the line passing through points (2, 3) and (5, 9)?",
    question_type: "multiple_choice",
    difficulty_level: 2,
    explanation: "Slope = (y₂ - y₁)/(x₂ - x₁) = (9 - 3)/(5 - 2) = 6/3 = 2.",
    created_at: new Date().toISOString(),
    options: [
      { id: "25a", question_id: "25", option_text: "1", is_correct: false, option_order: 1 },
      { id: "25b", question_id: "25", option_text: "2", is_correct: true, option_order: 2 },
      { id: "25c", question_id: "25", option_text: "3", is_correct: false, option_order: 3 },
      { id: "25d", question_id: "25", option_text: "4", is_correct: false, option_order: 4 },
    ],
  },
  {
    id: "26",
    subject_id: "math",
    question_text: "What is the y-intercept of the line y = 3x - 7?",
    question_type: "multiple_choice",
    difficulty_level: 1,
    explanation: "In the form y = mx + b, the y-intercept is b. For y = 3x - 7, the y-intercept is -7.",
    created_at: new Date().toISOString(),
    options: [
      { id: "26a", question_id: "26", option_text: "3", is_correct: false, option_order: 1 },
      { id: "26b", question_id: "26", option_text: "7", is_correct: false, option_order: 2 },
      { id: "26c", question_id: "26", option_text: "-7", is_correct: true, option_order: 3 },
      { id: "26d", question_id: "26", option_text: "-3", is_correct: false, option_order: 4 },
    ],
  },
  {
    id: "27",
    subject_id: "math",
    question_text: "What is the vertex of the parabola y = x² - 4x + 3?",
    question_type: "multiple_choice",
    difficulty_level: 3,
    explanation: "For y = ax² + bx + c, the vertex is at x = -b/(2a) = -(-4)/(2×1) = 2. Substituting: y = 2² - 4(2) + 3 = 4 - 8 + 3 = -1. Vertex: (2, -1).",
    created_at: new Date().toISOString(),
    options: [
      { id: "27a", question_id: "27", option_text: "(2, 1)", is_correct: false, option_order: 1 },
      { id: "27b", question_id: "27", option_text: "(-2, -1)", is_correct: false, option_order: 2 },
      { id: "27c", question_id: "27", option_text: "(2, -1)", is_correct: true, option_order: 3 },
      { id: "27d", question_id: "27", option_text: "(-2, 1)", is_correct: false, option_order: 4 },
    ],
  },
  {
    id: "28",
    subject_id: "math",
    question_text: "Which graph represents the function f(x) = |x - 2|?",
    question_type: "multiple_choice",
    difficulty_level: 2,
    explanation: "The function f(x) = |x - 2| is a V-shaped graph with its vertex at (2, 0), opening upward. It has slope -1 for x < 2 and slope +1 for x > 2.",
    created_at: new Date().toISOString(),
    options: [
      { id: "28a", question_id: "28", option_text: "V-shaped graph with vertex at (2, 0)", is_correct: true, option_order: 1 },
      { id: "28b", question_id: "28", option_text: "V-shaped graph with vertex at (-2, 0)", is_correct: false, option_order: 2 },
      { id: "28c", question_id: "28", option_text: "Straight line with slope 1", is_correct: false, option_order: 3 },
      { id: "28d", question_id: "28", option_text: "Parabola opening upward", is_correct: false, option_order: 4 },
    ],
  },
  {
    id: "29",
    subject_id: "math",
    question_text: "What is the domain of the function f(x) = √(x - 3)?",
    question_type: "multiple_choice",
    difficulty_level: 2,
    explanation: "For √(x - 3) to be defined, the expression under the square root must be non-negative: x - 3 ≥ 0, so x ≥ 3. Domain: [3, ∞).",
    created_at: new Date().toISOString(),
    options: [
      { id: "29a", question_id: "29", option_text: "All real numbers", is_correct: false, option_order: 1 },
      { id: "29b", question_id: "29", option_text: "x ≥ 3", is_correct: true, option_order: 2 },
      { id: "29c", question_id: "29", option_text: "x ≤ 3", is_correct: false, option_order: 3 },
      { id: "29d", question_id: "29", option_text: "x > 3", is_correct: false, option_order: 4 },
    ],
  },
  {
    id: "30",
    subject_id: "math",
    question_text: "What is the range of the function f(x) = x² + 2?",
    question_type: "multiple_choice",
    difficulty_level: 2,
    explanation: "Since x² ≥ 0 for all real x, we have x² + 2 ≥ 2. The minimum value is 2, and the function can take any value ≥ 2. Range: [2, ∞).",
    created_at: new Date().toISOString(),
    options: [
      { id: "30a", question_id: "30", option_text: "All real numbers", is_correct: false, option_order: 1 },
      { id: "30b", question_id: "30", option_text: "y ≥ 0", is_correct: false, option_order: 2 },
      { id: "30c", question_id: "30", option_text: "y ≥ 2", is_correct: true, option_order: 3 },
      { id: "30d", question_id: "30", option_text: "y ≤ 2", is_correct: false, option_order: 4 },
    ],
  },
  {
    id: "31",
    subject_id: "math",
    question_text: "Which equation represents a horizontal line?",
    question_type: "multiple_choice",
    difficulty_level: 1,
    explanation: "A horizontal line has the form y = constant. The equation y = 5 represents a horizontal line at y = 5.",
    created_at: new Date().toISOString(),
    options: [
      { id: "31a", question_id: "31", option_text: "y = 5", is_correct: true, option_order: 1 },
      { id: "31b", question_id: "31", option_text: "x = 5", is_correct: false, option_order: 2 },
      { id: "31c", question_id: "31", option_text: "y = x + 5", is_correct: false, option_order: 3 },
      { id: "31d", question_id: "31", option_text: "y = 5x", is_correct: false, option_order: 4 },
    ],
  },
  {
    id: "32",
    subject_id: "math",
    question_text: "What is the x-intercept of the line 2x + 3y = 6?",
    question_type: "multiple_choice",
    difficulty_level: 2,
    explanation: "To find the x-intercept, set y = 0: 2x + 3(0) = 6, so 2x = 6, x = 3. The x-intercept is (3, 0).",
    created_at: new Date().toISOString(),
    options: [
      { id: "32a", question_id: "32", option_text: "2", is_correct: false, option_order: 1 },
      { id: "32b", question_id: "32", option_text: "3", is_correct: true, option_order: 2 },
      { id: "32c", question_id: "32", option_text: "6", is_correct: false, option_order: 3 },
      { id: "32d", question_id: "32", option_text: "1", is_correct: false, option_order: 4 },
    ],
  },
  // Area and Volume Questions with Images
  {
    id: "33",
    subject_id: "math",
    question_text: "A rectangular garden has length 12m and width 8m. What is its area?",
    question_type: "multiple_choice",
    difficulty_level: 1,
    explanation: "Area of rectangle = length × width = 12m × 8m = 96m².",
    image_url: "/math-images/rectangle-12x8.svg",
    created_at: new Date().toISOString(),
    options: [
      { id: "33a", question_id: "33", option_text: "96m²", is_correct: true, option_order: 1 },
      { id: "33b", question_id: "33", option_text: "48m²", is_correct: false, option_order: 2 },
      { id: "33c", question_id: "33", option_text: "20m²", is_correct: false, option_order: 3 },
      { id: "33d", question_id: "33", option_text: "40m²", is_correct: false, option_order: 4 },
    ],
  },
  {
    id: "34",
    subject_id: "math",
    question_text: "A triangular field has base 10m and height 6m. Find its area.",
    question_type: "multiple_choice",
    difficulty_level: 2,
    explanation: "Area of triangle = (1/2) × base × height = (1/2) × 10m × 6m = 30m².",
    image_url: "/math-images/triangle-10x6.svg",
    created_at: new Date().toISOString(),
    options: [
      { id: "34a", question_id: "34", option_text: "60m²", is_correct: false, option_order: 1 },
      { id: "34b", question_id: "34", option_text: "30m²", is_correct: true, option_order: 2 },
      { id: "34c", question_id: "34", option_text: "16m²", is_correct: false, option_order: 3 },
      { id: "34d", question_id: "34", option_text: "36m²", is_correct: false, option_order: 4 },
    ],
  },
  {
    id: "35",
    subject_id: "math",
    question_text: "A circular pond has radius 5m. What is its area?",
    question_type: "multiple_choice",
    difficulty_level: 2,
    explanation: "Area of circle = πr² = π(5)² = 25π m².",
    image_url: "/math-images/circle-radius-5.svg",
    created_at: new Date().toISOString(),
    options: [
      { id: "35a", question_id: "35", option_text: "10π m²", is_correct: false, option_order: 1 },
      { id: "35b", question_id: "35", option_text: "25π m²", is_correct: true, option_order: 2 },
      { id: "35c", question_id: "35", option_text: "50π m²", is_correct: false, option_order: 3 },
      { id: "35d", question_id: "35", option_text: "5π m²", is_correct: false, option_order: 4 },
    ],
  },
  {
    id: "36",
    subject_id: "math",
    question_text: "A cube has side length 4cm. What is its volume?",
    question_type: "multiple_choice",
    difficulty_level: 2,
    explanation: "Volume of cube = side³ = 4³ = 64 cm³.",
    image_url: "/math-images/cube-side-4.svg",
    created_at: new Date().toISOString(),
    options: [
      { id: "36a", question_id: "36", option_text: "16 cm³", is_correct: false, option_order: 1 },
      { id: "36b", question_id: "36", option_text: "32 cm³", is_correct: false, option_order: 2 },
      { id: "36c", question_id: "36", option_text: "64 cm³", is_correct: true, option_order: 3 },
      { id: "36d", question_id: "36", option_text: "128 cm³", is_correct: false, option_order: 4 },
    ],
  },
  {
    id: "37",
    subject_id: "math",
    question_text: "A sphere has radius 3cm. What is its volume?",
    question_type: "multiple_choice",
    difficulty_level: 3,
    explanation: "Volume of sphere = (4/3)πr³ = (4/3)π(3)³ = (4/3)π(27) = 36π cm³.",
    image_url: "/math-images/sphere-radius-3.svg",
    created_at: new Date().toISOString(),
    options: [
      { id: "37a", question_id: "37", option_text: "27π cm³", is_correct: false, option_order: 1 },
      { id: "37b", question_id: "37", option_text: "36π cm³", is_correct: true, option_order: 2 },
      { id: "37c", question_id: "37", option_text: "108π cm³", is_correct: false, option_order: 3 },
      { id: "37d", question_id: "37", option_text: "9π cm³", is_correct: false, option_order: 4 },
    ],
  },
  {
    id: "38",
    subject_id: "math",
    question_text: "A rectangular box has length 6cm, width 4cm, and height 3cm. What is its volume?",
    question_type: "multiple_choice",
    difficulty_level: 2,
    explanation: "Volume of rectangular box = length × width × height = 6cm × 4cm × 3cm = 72 cm³.",
    image_url: "/math-images/rectangular-box-6x4x3.svg",
    created_at: new Date().toISOString(),
    options: [
      { id: "38a", question_id: "38", option_text: "72 cm³", is_correct: true, option_order: 1 },
      { id: "38b", question_id: "38", option_text: "36 cm³", is_correct: false, option_order: 2 },
      { id: "38c", question_id: "38", option_text: "144 cm³", is_correct: false, option_order: 3 },
      { id: "38d", question_id: "38", option_text: "13 cm³", is_correct: false, option_order: 4 },
    ],
  },
  {
    id: "39",
    subject_id: "math",
    question_text: "A trapezoid has parallel sides of 8m and 12m, and height 5m. What is its area?",
    question_type: "multiple_choice",
    difficulty_level: 3,
    explanation: "Area of trapezoid = (1/2) × (sum of parallel sides) × height = (1/2) × (8 + 12) × 5 = (1/2) × 20 × 5 = 50 m².",
    image_url: "/math-images/trapezoid-8-12-5.svg",
    created_at: new Date().toISOString(),
    options: [
      { id: "39a", question_id: "39", option_text: "40 m²", is_correct: false, option_order: 1 },
      { id: "39b", question_id: "39", option_text: "50 m²", is_correct: true, option_order: 2 },
      { id: "39c", question_id: "39", option_text: "100 m²", is_correct: false, option_order: 3 },
      { id: "39d", question_id: "39", option_text: "25 m²", is_correct: false, option_order: 4 },
    ],
  },
  {
    id: "40",
    subject_id: "math",
    question_text: "A cone has radius 4cm and height 9cm. What is its volume?",
    question_type: "multiple_choice",
    difficulty_level: 3,
    explanation: "Volume of cone = (1/3)πr²h = (1/3)π(4)²(9) = (1/3)π(16)(9) = 48π cm³.",
    image_url: "/math-images/cone-radius-4-height-9.svg",
    created_at: new Date().toISOString(),
    options: [
      { id: "40a", question_id: "40", option_text: "36π cm³", is_correct: false, option_order: 1 },
      { id: "40b", question_id: "40", option_text: "48π cm³", is_correct: true, option_order: 2 },
      { id: "40c", question_id: "40", option_text: "144π cm³", is_correct: false, option_order: 3 },
      { id: "40d", question_id: "40", option_text: "12π cm³", is_correct: false, option_order: 4 },
    ],
  },
]

export const mockExams: Exam[] = [
  {
    id: "1",
    title: "Mathematics Practice Test - 2024",
    description: "Comprehensive mathematics practice covering algebra, calculus, geometry, derivation, integration, graphing, area, and volume with 40+ questions including visual problems",
    field: "natural",
    subject_id: "math",
    batch: 2024,
    year: 2024,
    duration_minutes: 150,
    total_marks: 400,
    passing_marks: 200,
    is_active: true,
    created_at: new Date().toISOString(),
    questions: mockQuestions.filter((q) => q.subject_id === "math"),
  },
  {
    id: "2",
    title: "Physics Practice Test",
    description: "Physics practice focusing on mechanics and thermodynamics",
    field: "natural",
    subject_id: "physics",
    batch: 2024,
    year: 2024,
    duration_minutes: 45,
    total_marks: 50,
    passing_marks: 25,
    is_active: true,
    created_at: new Date().toISOString(),
    questions: mockQuestions.filter((q) => q.subject_id === "physics"),
  },
  {
    id: "3",
    title: "Chemistry Practice Test",
    description: "General and organic chemistry practice questions",
    field: "natural",
    subject_id: "chemistry",
    batch: 2023,
    year: 2023,
    duration_minutes: 45,
    total_marks: 50,
    passing_marks: 25,
    is_active: true,
    created_at: new Date().toISOString(),
    questions: mockQuestions.filter((q) => q.subject_id === "chemistry"),
  },
  {
    id: "4",
    title: "Biology Practice Test",
    description: "Life sciences and biology fundamentals",
    field: "natural",
    subject_id: "biology",
    batch: 2023,
    year: 2023,
    duration_minutes: 45,
    total_marks: 50,
    passing_marks: 25,
    is_active: true,
    created_at: new Date().toISOString(),
    questions: mockQuestions.filter((q) => q.subject_id === "biology"),
  },
  {
    id: "5",
    title: "History Practice Test",
    description: "Ethiopian and world history comprehensive review",
    field: "social",
    subject_id: "history",
    batch: 2024,
    year: 2024,
    duration_minutes: 60,
    total_marks: 100,
    passing_marks: 50,
    is_active: true,
    created_at: new Date().toISOString(),
    questions: mockQuestions.filter((q) => q.subject_id === "history"),
  },
]

export function getExamsByField(field: ExamField): Exam[] {
  return mockExams.filter((exam) => exam.field === field)
}

export function getSubjectsByField(field: ExamField): Subject[] {
  return mockSubjects.filter((subject) => subject.field === field)
}
